version: "3"
services:
  # Backend container
  api:
    container_name: innobackend-api
    # Set build context as current folder, use dev Dockerfile.
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Bind current folder to dockerfile workdir in order to reflect local changes to container without having to build.
    volumes:
      - .:/app
    # Create port mapping between computer port and container port.
    ports:
      - ${PORT}:${PORT}
    # Make sure that the database is created before starting the server.
    depends_on:
      - mongo

  # Mongdodb container.
  mongo:
    container_name: innobackend-mongo
    image: mongo:7.0.3-jammy
    restart: always
    # Persist dev database with database volume
    volumes:
      - database:/data/db
    # Basic health check with short interval. Useful in a dev setting.
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 1s
      retries: 10
    # Use the username and password defined in .env as mongodb root user definition.
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    # Mongo heavily clutters the logs, so all output is just routed to dev/null. Can be disabled for debugging purposes if necessary
    command: --logpath /dev/null

  # A simple mongdodb admin page container. Accessed at http://localhost:8081
  mongo-express:
    container_name: innobackend-mongo-express
    image: mongo-express:1.0.0-20-alpine3.18
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URI}
    depends_on:
      - mongo

# Dev database volume
volumes:
  database:
